[workspace]

members = [
    "crates/atiny-cli",
    "crates/atiny-parser",
    "crates/atiny-checker",
    "crates/atiny-error",
    "crates/atiny-tree",
    "crates/atiny-location",
    "crates/atiny-tests",
]